# Generated by Django 4.2.7 on 2025-09-21 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiographModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('record_text', models.TextField(blank=True, null=True)),
                ('record_time', models.IntegerField(default=0)),
                ('words_count', models.CharField(blank=True, max_length=120, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('record_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('biograph_type', models.CharField(choices=[('1', 'SIMPLE'), ('2', 'VIDEO')], default='1', max_length=1)),
                ('all_keywords', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('co_authors', models.JSONField(blank=True, default=list)),
                ('books', models.JSONField(blank=True, default=list)),
                ('monologues', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('status_key', models.IntegerField(default=1)),
                ('last_played_record', models.CharField(default='', max_length=120)),
                ('last_updated_title', models.JSONField(blank=True, default=dict)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('migrated_from_old_system', models.BooleanField(default=False)),
                ('old_biograph_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biographs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biograph',
                'verbose_name_plural': 'Biographs',
                'db_table': 'biographs',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('product_id', models.CharField(default='', max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('migrated_from_old_system', models.BooleanField(default=False)),
                ('old_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RecordedTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening_time', models.IntegerField()),
                ('date_of_listening', models.DateField(default=django.utils.timezone.now)),
                ('is_removed', models.BooleanField(default=False)),
                ('status_key', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('migrated_from_old_system', models.BooleanField(default=False)),
                ('old_recorded_time_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_times', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recorded Time',
                'verbose_name_plural': 'Recorded Times',
                'db_table': 'recorded_times',
                'ordering': ['-date_of_listening'],
            },
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved Request'), (3, 'Added Co-Author'), (4, 'New Record in Biograph'), (5, 'Request to publish record'), (6, 'Subscribe')], default=1)),
                ('is_read', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('status_key', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('migrated_from_old_system', models.BooleanField(default=False)),
                ('old_notification_id', models.CharField(blank=True, max_length=100, null=True)),
                ('biograph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biograph.biographmodel')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('synopsis', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('biographs', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('status_key', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('migrated_from_old_system', models.BooleanField(default=False)),
                ('old_book_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CoAuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('migrated_from_old_system', models.BooleanField(default=False)),
                ('old_coauthor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('biograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_author_relationships', to='biograph.biographmodel')),
                ('co_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_authored_biographs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Co-Author',
                'verbose_name_plural': 'Co-Authors',
                'db_table': 'co_authors',
                'unique_together': {('biograph', 'co_author')},
            },
        ),
    ]
